// src/app/components/Autocomplete.jsx
import { useEffect, useState } from "react";
import "./Autocomplete.css";

function Autocomplete({ options }) {
  const [value, setValue] = useState("");
  const [suggestions, setSuggestions] = useState([]);

  useEffect(() => {
    const timer = setTimeout(() => {
      if (!value.trim()) {
        setSuggestions([]);
        return;
      }// timer当中 若是没有值 就设置为空

      const search = value.toLowerCase();
      setSuggestions(
        options.filter((option) => option.toLowerCase().includes(search)),
      );//有值就设置成我们都要的
    }, 300);

    return () => clearTimeout(timer);
  }, [options, value]);



  function selectOption(option) {
    setValue(option);
    setSuggestions([]);
  }

  return (
    <div className="autocomplete">
      <input
        value={value}
        placeholder="Search technology"
        onChange={(event) => setValue(event.target.value)}
      />

      {suggestions.map((option) => (
        <button
          key={option}
          type="button"
          onClick={() => selectOption(option)}
        >
          {option}
        </button>
      ))}
    </div>
  );
}

export default Autocomplete;

// src/app/practice/components/autocomplete/autocomplete.component.ts
import { Component, OnDestroy } from '@angular/core';

@Component({
  selector: 'app-practice-autocomplete',
  templateUrl: './autocomplete.component.html',
  styleUrls: ['./autocomplete.component.css']
})
export class AutocompleteComponent implements OnDestroy {
  autocomplete = '';
  suggestions: string[] = [];
  private autocompleteTimer?: ReturnType<typeof setTimeout>;
  private readonly technologies = ['react', 'redux', 'router', 'vue', 'angular', 'node', 'next'];

  ngOnDestroy(): void {
    clearTimeout(this.autocompleteTimer);
  }

  updateAutocomplete(): void {
    clearTimeout(this.autocompleteTimer);
    this.autocompleteTimer = setTimeout(() => {
      const value = this.autocomplete.trim().toLowerCase();
      this.suggestions = value ? this.technologies.filter(item => item.includes(value)) : [];
    }, 300);
  }

  selectSuggestion(value: string): void {
    this.autocomplete = value;
    this.suggestions = [];
  }
}

<h2>Autocomplete</h2>
<input [(ngModel)]="autocomplete" (ngModelChange)="updateAutocomplete()" placeholder="Search technology" />
<button class="suggestion" *ngFor="let item of suggestions" (click)="selectSuggestion(item)">
  {{ item }}
</button>
