// src/app/practice/components/accordion/accordion.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-practice-accordion',
  templateUrl: './accordion.component.html',
  styleUrls: ['./accordion.component.css']
})
export class AccordionComponent {
  openAccordion: number | null = null;
  accordionItems = [
    { title: 'React', content: 'React is a UI library.' },
    { title: 'Vue', content: 'Vue is a frontend framework.' },
    { title: 'Angular', content: 'Angular is a full framework.' }
  ];
}

<h2>Accordion</h2>
<div class="accordion-item" *ngFor="let item of accordionItems; let i = index">
  <button (click)="openAccordion = openAccordion === i ? null : i">
    {{ item.title }} <b>{{ openAccordion === i ? "-" : "+" }}</b>
  </button>
  <p *ngIf="openAccordion === i">{{ item.content }}</p>
</div>

// src/app/components/Accordion.jsx
import { useState } from "react";
import "./Accordion.css";
const data = [
  { title: "React", content: "React is a UI library." },
  { title: "Vue", content: "Vue is a frontend framework." },
  { title: "Angular", content: "Angular is a full framework." },

];
function Accordion() {
  const [openIndex, setOpenIndex] = useState(null);
  const items = data
  function toggleItem(index) {
    setOpenIndex((current) => (current === index ? null : index));
  }

  return (
    <div className="accordion">
      {items.map((item, index) => {
        const isOpen = openIndex === index;

        return (
          <div className="accordion-item" key={item.title}>
            <button
              type="button"
              className="accordion-title"
              aria-expanded={isOpen}
              onClick={() => toggleItem(index)}
            >
              {item.title}
              <span>{isOpen ? "-" : "+"}</span>
            </button>

            {isOpen && <div className="accordion-content">{item.content}</div>}
          </div>
        );
      })}
    </div>
  );
}

export default Accordion;
