// src/app/practice/components/chat-ui/chat-ui.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-practice-chat-ui',
  templateUrl: './chat-ui.component.html',
  styleUrls: ['./chat-ui.component.css']
})
export class ChatUiComponent {
  messages = [{ role: 'assistant', text: 'Hi, how can I help you?' }];
  chatInput = '';
  replying = false;

  sendMessage(): void {
    const text = this.chatInput.trim();
    if (!text || this.replying) return;
    this.messages.push({ role: 'user', text });
    this.chatInput = '';
    this.replying = true;
    setTimeout(() => {
      this.messages.push({ role: 'assistant', text: `You said: "${text}"` });
      this.replying = false;
    }, 800);
  }
}

<h2>ChatUI</h2>
<div class="chat">
  <p *ngFor="let message of messages" [class.user]="message.role === 'user'">{{ message.text }}</p>
  <em *ngIf="replying">Assistant is typing...</em>
</div>
<div class="row">
  <input [(ngModel)]="chatInput" (keyup.enter)="sendMessage()" placeholder="Message ChatGPT" />
  <button (click)="sendMessage()" [disabled]="replying">Send</button>
</div>

// src/app/components/ChatUI.jsx
import { useEffect, useRef, useState } from "react";
import "./ChatUI.css";

function ChatUI() {
  const [messages, setMessages] = useState([
    { id: 1, role: "assistant", text: "Hi, how can I help you?" },
  ]);
  const [input, setInput] = useState("");
  const [isReplying, setIsReplying] = useState(false);
  const timerRef = useRef(null);

  useEffect(() => {
    return () => clearTimeout(timerRef.current);
  }, []);

  function sendMessage(event) {
    event.preventDefault();

    const text = input.trim();
    if (!text || isReplying) return;

    setMessages((current) => [
      ...current,
      { id: crypto.randomUUID(), role: "user", text },
    ]);

    setInput("");

    
    setIsReplying(true);
    timerRef.current = setTimeout(() => {
      setMessages((current) => [
        ...current,
        {
          id: crypto.randomUUID(),
          role: "assistant",
          text: `You said: "${text}"`,
        },
      ]);
      setIsReplying(false);
    }, 800);
  }

  return (
    <div className="chat-ui">
      <div className="chat-messages">
        {messages.map((message) => (
          <div
            key={message.id}
            className={`chat-message ${message.role}`}
          >
            <span>{message.text}</span>
          </div>
        ))}

        {isReplying && <p className="chat-status">Assistant is typing...</p>}
      </div>

      <form className="chat-form" onSubmit={sendMessage}>
        <input
          value={input}
          placeholder="Message ChatGPT"
          onChange={(event) => setInput(event.target.value)}
        />
        <button type="submit" disabled={isReplying}>
          Send
        </button>
      </form>
    </div>
  );
}

export default ChatUI;
