// src/app/practice/components/multi-select-dropdown/multi-select-dropdown.component.ts
import { Component } from '@angular/core';

type Option = { label: string; value: string };

@Component({
  selector: 'app-practice-multi-select-dropdown',
  templateUrl: './multi-select-dropdown.component.html',
  styleUrls: ['./multi-select-dropdown.component.css']
})
export class MultiSelectDropdownComponent {
  selectedFruits: string[] = [];
  multiOpen = false;
  readonly options: Option[] = [
    { label: 'Apple', value: 'apple' },
    { label: 'Banana', value: 'banana' },
    { label: 'Orange', value: 'orange' }
  ];

  toggleFruit(value: string): void {
    this.selectedFruits = this.selectedFruits.includes(value)
      ? this.selectedFruits.filter(item => item !== value)
      : [...this.selectedFruits, value];
  }
}

<h2>MultiSelectDropdown</h2>
<div class="dropdown">
  <button (click)="multiOpen = !multiOpen">{{ selectedFruits.join(", ") || "Select options" }} ▾</button>
  <div class="menu" *ngIf="multiOpen">
    <label *ngFor="let option of options">
      <input type="checkbox" [checked]="selectedFruits.includes(option.value)" (change)="toggleFruit(option.value)" />
      {{ option.label }}
    </label>
  </div>
</div>

// src/app/components/MultiSelectDropdown.jsx
import { useState } from "react";
import "./MultiSelectDropdown.css";

function MultiSelectDropdown({ options, value, onChange }) {
  const [isOpen, setIsOpen] = useState(false);

  function toggleOption(optionValue) {
    if (value.includes(optionValue)) {
      onChange(value.filter((item) => item !== optionValue));
    } else {
      onChange([...value, optionValue]);
    }
  }

  const selectedLabels = options
    .filter((option) => value.includes(option.value))
    .map((option) => option.label);

  return (
    <div className="multi-select">
      <button
        type="button"
        className="multi-select-trigger"
        aria-expanded={isOpen}
        onClick={() => setIsOpen(!isOpen)}
      >
        {selectedLabels.length > 0
          ? selectedLabels.join(", ")
          : "Select options"}
        <span>{isOpen ? "▲" : "▼"}</span>
      </button>

      {isOpen && (
        <div className="multi-select-menu">
          {options.map((option) => (
            <label key={option.value}>
              <input
                type="checkbox"
                checked={value.includes(option.value)}
                onChange={() => toggleOption(option.value)}
              />
              {option.label}
            </label>
          ))}
        </div>
      )}
    </div>
  );
}

export default MultiSelectDropdown;
