// src/app/practice/components/progress-bar/progress-bar.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-practice-progress-bar',
  templateUrl: './progress-bar.component.html',
  styleUrls: ['./progress-bar.component.css']
})
export class ProgressBarComponent {
  progress = 30;

  adjustProgress(amount: number): void {
    this.progress = Math.max(0, Math.min(100, this.progress + amount));
  }
}

<h2>ProgressBar</h2>
<div class="progress-track">
  <span [style.width.%]="progress">{{ progress }}%</span>
</div>
<div class="row">
  <button (click)="adjustProgress(-1)">-1</button>
  <button (click)="adjustProgress(1)">+1</button>
</div>

// src/app/components/ProgressBar.jsx
import { useState } from "react";
import "./ProgressBar.css";

function ProgressBar({ value }) {
  const max = Math.max(0, value)
  const progress = Math.min(100, max);

  return (
    <div
      className="progress-bar"
      role="progressbar"
      aria-valuemin="0"
      aria-valuemax="100"
      aria-valuenow={progress}
    >
      <div className="progress-fill" style={{ width: `${progress}%` }}>
        {progress}%
      </div>
    </div>
  );
}

export function ProgressBarDemo() {
  const [progress, setProgress] = useState(30);

  return (
    <div>
      <ProgressBar value={progress} />

      <button onClick={() => setProgress((current) => current - 1)}>
        -1
      </button>
      <button onClick={() => setProgress((current) => current + 1)}>
        +1
      </button>
    </div>
  );
}

export default ProgressBar;
