// src/app/practice/components/search-box/search-box.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-practice-search-box',
  templateUrl: './search-box.component.html',
  styleUrls: ['./search-box.component.css']
})
export class SearchBoxComponent {
  search = '';
  selectedSearch = false;
  private readonly fruits = ['Apple', 'Banana', 'Blueberry', 'Orange', 'Strawberry'];

  get filteredFruit(): string[] {
    return this.selectedSearch
      ? []
      : this.fruits.filter(item => item.toLowerCase().includes(this.search.toLowerCase()));
  }

  markDirty(): void {
    this.selectedSearch = false;
  }

  selectSearch(item: string): void {
    this.search = item;
    this.selectedSearch = true;
  }
}

<h2>SearchBox</h2>
<input [(ngModel)]="search" (ngModelChange)="markDirty()" placeholder="Search fruit" />
<button class="suggestion" *ngFor="let item of filteredFruit" (click)="selectSearch(item)">
  {{ item }}
</button>

// src/app/components/SearchBox.jsx
import { useState } from "react";

const searchItems = [
  "Apple",
  "Banana",
  "Blueberry",
  "Orange",
  "Strawberry",
];

function SearchBox() {
  const [search, setSearch] = useState("");
  const [selected, setSelected] = useState(false);

  const filteredItems = selected
    ? []
    : searchItems.filter((item) =>
        item.toLowerCase().includes(search.toLowerCase()),
      );

  const handleSelect = (item) => {
    setSearch(item);
    setSelected(true);
  };

  return (
    <div>
      <h2>Search Box</h2>

      <input
        value={search}
        placeholder="Search fruit"
        onChange={(event) => {
          setSearch(event.target.value);
          setSelected(false);
        }}
      />

      <ul>
        {filteredItems.map((item) => (
          <li key={item} onClick={() => handleSelect(item)}>
            {item}
          </li>
        ))}
      </ul>
    </div>
  );
}

export default SearchBox;
