// src/app/practice/components/todo-list/todo-list.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-practice-todo-list',
  templateUrl: './todo-list.component.html',
  styleUrls: ['./todo-list.component.css']
})
export class TodoListComponent {
  task = '';
  tasks: string[] = [];

  addTask(): void {
    if (!this.task.trim()) return;
    this.tasks.push(this.task.trim());
    this.task = '';
  }

  removeTask(index: number): void {
    this.tasks.splice(index, 1);
  }

  moveTask(index: number, amount: number): void {
    const target = index + amount;
    if (target < 0 || target >= this.tasks.length) return;
    [this.tasks[index], this.tasks[target]] = [this.tasks[target], this.tasks[index]];
  }
}

<h2>ToDoList</h2>
<div class="row">
  <input [(ngModel)]="task" (keyup.enter)="addTask()" placeholder="Please input a task" />
  <button (click)="addTask()">Submit</button>
</div>
<ul>
  <li *ngFor="let item of tasks; let i = index">
    <span (click)="removeTask(i)">{{ item }}</span>
    <button (click)="moveTask(i, -1)" [disabled]="i === 0">Up</button>
    <button (click)="moveTask(i, 1)" [disabled]="i === tasks.length - 1">Down</button>
  </li>
</ul>

// src/app/components/ToDoList.jsx
import { useState } from "react";

function ToDoList() {
  const [list, setList] = useState([]);
  const [value, setTask] = useState("");
  
  const submit = () => {
    if (value !== "") {
      const next = [...list, { id: value, name: value }];
      setList(next);
      setTask("");
    }
  };

  const handleCancel = (id) => {
    const next = list.filter((item) => item.id !== id);
    setList(next);
  };

  const handleSeq = (flag, id) => {
    const index = list.findIndex((item) => item.id === id);
    const nextIndex = flag ? index - 1 : index + 1;

    if (index === -1 || nextIndex < 0 || nextIndex >= list.length) {
      return;
    }

    const next = [...list];
    [next[index], next[nextIndex]] = [next[nextIndex], next[index]];
    setList(next);
  };

  return (
    <>
      <input
        value={value}
        placeholder={"Please Input a task"}
        onChange={(e) => setTask(e.target.value)}
      />

      <button onClick={submit}>submit </button>
      <ul>
        {list.map((item) => {
          return (
            <>
              <li key={item.id} onClick={() => handleCancel(item.id)}>
                {item.name}
              </li>
              <button onClick={() => handleSeq(true, item.id)}>Up</button>
              <button onClick={() => handleSeq(false, item.id)}>Down</button>
            </>
          );
        })}
      </ul>
    </>
  );
}

export default ToDoList;
