// src/app/components/Calendar.jsx
import { useState } from "react";
import "./Calendar.css";

const weekDays = ["日", "一", "二", "三", "四", "五", "六"];

function Calendar() {
  const today = new Date();
  const [currentMonth, setCurrentMonth] = useState(
    new Date(today.getFullYear(), today.getMonth(), 1),
  );
  const [selectedDay, setSelectedDay] = useState(today.getDate());

  const year = currentMonth.getFullYear();
  const month = currentMonth.getMonth();
  const firstDay = new Date(year, month, 1).getDay();
  const daysInMonth = new Date(year, month + 1, 0).getDate();

  const days = [
    ...Array(firstDay).fill(null),
    ...Array.from({ length: daysInMonth }, (_, index) => index + 1),
  ];

  function changeMonth(amount) {
    setCurrentMonth(new Date(year, month + amount, 1));
    setSelectedDay(null);
  }

  return (
    <div className="calendar">
      <header className="calendar-header">
        <button onClick={() => changeMonth(-1)}>上一月</button>
        <h2>
          {year} 年 {month + 1} 月
        </h2>
        <button onClick={() => changeMonth(1)}>下一月</button>
      </header>

      <div className="calendar-grid">
        {weekDays.map((day) => (
          <strong key={day}>{day}</strong>
        ))}

        {days.map((day, index) => (
          <button
            key={index}
            className={day === selectedDay ? "selected" : ""}
            disabled={!day}
            onClick={() => setSelectedDay(day)}
          >
            {day}
          </button>
        ))}
      </div>

      {selectedDay && (
        <p>
          选择日期：{year}-{month + 1}-{selectedDay}
        </p>
      )}
    </div>
  );
}

export default Calendar;

// src/app/practice/components/calendar/calendar.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-practice-calendar',
  templateUrl: './calendar.component.html',
  styleUrls: ['./calendar.component.css']
})
export class CalendarComponent {
  readonly weekDays = ['日', '一', '二', '三', '四', '五', '六'];
  currentMonth = new Date(new Date().getFullYear(), new Date().getMonth(), 1);
  selectedDay: number | null = new Date().getDate();

  get calendarYear(): number {
    return this.currentMonth.getFullYear();
  }

  get calendarMonth(): number {
    return this.currentMonth.getMonth();
  }

  get calendarDays(): (number | null)[] {
    const blanks = Array(this.currentMonth.getDay()).fill(null);
    const days = new Date(this.calendarYear, this.calendarMonth + 1, 0).getDate();
    return [...blanks, ...Array.from({ length: days }, (_, index) => index + 1)];
  }

  changeMonth(amount: number): void {
    this.currentMonth = new Date(this.calendarYear, this.calendarMonth + amount, 1);
    this.selectedDay = null;
  }
}

<h2>Calendar</h2>
<div class="calendar-head">
  <button (click)="changeMonth(-1)">上一月</button>
  <b>{{ calendarYear }} 年 {{ calendarMonth + 1 }} 月</b>
  <button (click)="changeMonth(1)">下一月</button>
</div>
<div class="calendar-grid">
  <b *ngFor="let day of weekDays">{{ day }}</b>
  <button
    *ngFor="let day of calendarDays"
    [disabled]="!day"
    [class.primary]="day === selectedDay"
    (click)="selectedDay = day"
  >
    {{ day }}
  </button>
</div>
<p *ngIf="selectedDay">选择日期：{{ calendarYear }}-{{ calendarMonth + 1 }}-{{ selectedDay }}</p>
