// src/app/components/ClickOrderBoxes.jsx
import { useState } from "react";
import "./ClickOrderBoxes.css";

function ClickOrderBoxes({ count = 5 }) {
  const [clickOrder, setClickOrder] = useState([]);
  const [isResetting, setIsResetting] = useState(false);

  function handleClick(index) {
    if (isResetting || clickOrder.includes(index)) return;

    const nextOrder = [...clickOrder, index];
    setClickOrder(nextOrder);

    if (nextOrder.length === count) {
      resetInReverse(nextOrder);
    }
  }

  async function resetInReverse(order) {
    setIsResetting(true);

    for (const index of [...order].reverse()) {
      await wait(500);
      setClickOrder((current) => current.filter((item) => item !== index));//这步骤很重要呢
    }

    setIsResetting(false);
  }

  return (
    <div className="click-order-boxes">
      {Array.from({ length: count }, (_, index) => (
        <button
          key={index}
          type="button"
          className={clickOrder.includes(index) ? "order-box active" : "order-box"}
          onClick={() => handleClick(index)}
        />
      ))}
    </div>
  );
}

function wait(milliseconds) {
  return new Promise((resolve) => setTimeout(resolve, milliseconds));
}

export default ClickOrderBoxes;

// src/app/practice/components/click-order-boxes/click-order-boxes.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-practice-click-order-boxes',
  templateUrl: './click-order-boxes.component.html',
  styleUrls: ['./click-order-boxes.component.css']
})
export class ClickOrderBoxesComponent {
  clickOrder: number[] = [];
  resettingBoxes = false;
  readonly boxes = [0, 1, 2, 3, 4];

  async clickBox(index: number): Promise<void> {
    if (this.resettingBoxes || this.clickOrder.includes(index)) return;
    this.clickOrder.push(index);
    if (this.clickOrder.length !== this.boxes.length) return;
    this.resettingBoxes = true;
    for (const item of [...this.clickOrder].reverse()) {
      await new Promise(resolve => setTimeout(resolve, 350));
      this.clickOrder = this.clickOrder.filter(value => value !== item);
    }
    this.resettingBoxes = false;
  }
}

<h2>ClickOrderBoxes</h2>
<div class="click-boxes">
  <button *ngFor="let box of boxes" (click)="clickBox(box)" [class.active]="clickOrder.includes(box)">
    {{ clickOrder.indexOf(box) + 1 || "" }}
  </button>
</div>
