// src/app/components/Carousel.jsx
import { useState } from "react";
import "./Carousel.css";

function Carousel({ images }) {
  const [index, setIndex] = useState(0);

  function showPrevious() {
    setIndex((current) => (current - 1 + images.length) % images.length);
  }

  function showNext() {
    setIndex((current) => (current + 1) % images.length);
  }

  if (images.length === 0) return null;

  return (
    <div className="carousel">
      <button type="button" onClick={showPrevious}>
        Prev
      </button>

      <img src={images[index]} alt={`Slide ${index + 1}`} />
      {/* /这是核心 */}

      <button type="button" onClick={showNext}>
        Next
      </button>
    </div>
  );
}

export default Carousel;

// src/app/practice/components/carousel/carousel.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-practice-carousel',
  templateUrl: './carousel.component.html',
  styleUrls: ['./carousel.component.css']
})
export class CarouselComponent {
  carouselIndex = 0;
  readonly carouselImages = [
    'https://picsum.photos/seed/carousel-1/300/180',
    'https://picsum.photos/seed/carousel-2/300/180',
    'https://picsum.photos/seed/carousel-3/300/180'
  ];

  previousImage(): void {
    this.carouselIndex = (this.carouselIndex - 1 + this.carouselImages.length) % this.carouselImages.length;
  }

  nextImage(): void {
    this.carouselIndex = (this.carouselIndex + 1) % this.carouselImages.length;
  }
}

<h2>Carousel</h2>
<div class="carousel">
  <button (click)="previousImage()">Prev</button>
  <img [src]="carouselImages[carouselIndex]" [alt]="'Slide ' + (carouselIndex + 1)" />
  <button (click)="nextImage()">Next</button>
</div>
